name: Release Creation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: self-hosted
    env:
      DOTNET_INSTALL_DIR: "~/.dotnet"
      DB_CONNECTION_STRING: ${{secrets.DB_CONNECTION_STRING}}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.3.1
      with:
        dotnet-version: 9.0.x
    - name: Restore Tools
      run: dotnet tool restore
    - name: Restore Dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Stop the Application Service
      run: sudo systemctl stop GameMasterBot.service
    - name: Publish
      run: dotnet publish -c Release -o ~/GameMasterBot
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Start the Application Service
      run: sudo systemctl start GameMasterBot.service

    - name: Post Release to Discord Channel
      id: post_release_to_discord
      uses: SethCohen/github-releases-to-discord@v1.13.1
      with:
        webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        color: "3447003"
        content: "A new release of GameMasterBot just dropped!"
